Section "InputClass"
        Identifier "libinput touchpad catchall backup"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event5"
        Driver "libinput"
		Option "DisableWhileTyping" "true"
		Option "ClickMethod" "clickfinger"
		Option "NaturalScrolling" "true"
		Option "Tapping" "true"
		Option "TappingDrag" "true"
		Option "TappingDragLock" "true"
EndSection
