#!/usr/bin/sh

ACPI_RES=$(acpi -b)
ACPI_CODE=$?
if [ $ACPI_CODE -eq 0 ]
then
    BAT_LEVEL_ALL=$(echo "$ACPI_RES" | grep -v "unavailable" | grep -E -o "[0-9][0-9]?[0-9]?%")
    IS_CHARGING=$(echo "$ACPI_RES" | grep -v "unavailable" | awk '{ printf("%s\n", substr($3, 0, length($3)-1) ) }')

    echo "🗲$BAT_LEVEL_ALL"
    
    if [ "$IS_CHARGING" = "Discharging" ]
    then
        echo "#00FFFF"
    else
        if [ "${BAT_LEVEL_ALL}" -le 35 ]
        then
            echo "#FA1E44"
        else
            echo "#6298e0"
        fi
    fi
fi
