#!/usr/bin/sh

vstatus="$(amixer get Master | awk '/Right:/ {print $5}' | sed 's/[^0-9]//g; s/^0//')"
vicon=""

echo "$vicon $vstatus"%""

case $BLOCK_BUTTON in
	5) amixer set Master 5%- && amixer get Master | awk '/Right:/ {print $5}' | sed 's/[^0-9]//g; s/^0//' && pkill -SIGRTMIN+1 i3blocks &
		;;
	4) amixer set Master 5%+ && amixer get Master | awk '/Right:/ {print $5}' | sed 's/[^0-9]//g; s/^0//' && pkill -SIGRTMIN+1 i3blocks &
		;;
esac
