Section "Device"
    Identifier     "NVIDIA"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BusID          "PCI:1:0:0"
    Option         "PrimaryGPU" "Yes"
    Option         "AllowExternalGpus" "True"
    Option         "ConnectedMonitor" "DP-0"
    Option         "RandRRotation" "on"
EndSection

Section "Device"
    Identifier     "AMD"
    Driver         "amdgpu"
    VendorName     "Advanced Micro Devices, Inc. [AMD/ATI]"
    BusID          "PCI:5:0:0"
    Option         "PrimaryGPU" "No"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "NVIDIA"
    Monitor        "DP-0"
    DefaultDepth   24
    SubSection     "Display"
        Depth       24
        Modes       "2560x1080"
    EndSubSection
EndSection

Section "Monitor"
    Identifier     "DP-0"
    Option         "PreferredMode" "2560x1080"
        Option         "PreferredRefreshRate" "74.99"
    Option         "Primary" "Yes"
EndSection

Section "Files"
    ModulePath     "/usr/lib/nvidia/xorg"
    ModulePath     "/usr/lib/xorg/modules"
EndSection