[base]
session=/usr/bin/i3
greeter=/usr/libexec/lxdm-greeter-gtk

[server]
arg=/usr/bin/X -background vt7
[display]
gtk_theme=Breeze-Dark
bottom_pane=1
lang=0
keyboard=0
theme=BlackArch

[input]

[userlist]
disable=1
white=
black=

