enable_audio_bell no
background_opacity 0.6
inactive_background_opacity 0.2

enabled_layouts tall
map ctrl+h previous_window
map ctrl+k next_window
map ctrl+l launch --location=hsplit
map ctrl+j launch --location=vsplit
map ctrl+, edit_config_file
