#!/bin/sh

BLANK='#000000'
CLEAR='#000000'
DEFAULT='#6298E0'
TEXT='#6298E0'
WRONG='#E06298'
VERIFYING='#6298E0'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$WRONG          \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$WRONG         \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 1                     \
--clock                      \
--indicator                  \
--time-str="%H:%M"        \
--date-str="%Y-%m-%d"       \
