CPU_DRIVER_OPMODE_ON_AC=passive
CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_MIN_PERF_ON_AC=100
CPU_CSTATE_ON_AC=0
CPU_EIST_ON_AC=0
CPU_BOOST_ON_AC=1
CPU_CORES_ON_AC=all
PLATFORM_PROFILE_ON_AC=performance

CPU_DRIVER_OPMODE_ON_BAT=active
CPU_SCALING_GOVERNOR_ON_BAT=powersave
CPU_ENERGY_PERF_POLICY_ON_BAT=power
CPU_BOOST_ON_BAT=1
CPU_HWP_DYN_BOOST_ON_BAT=1
START_CHARGE_THRESH_BAT0=0
STOP_CHARGE_THRESH_BAT0=100
PLATFORM_PROFILE_ON_BAT=quiet
